/**
 * Core framework types
 */

/** Cloudflare Worker env â€" consumers define their own Env type */
export type Env = Record<string, any>;

export type MaybePromise<T> = T | Promise<T>;

/** Route context â€" passed to load functions, actions, and server utilities */
export interface RouteContext<E = Env> {
  /** The incoming Request (standard Web API) */
  request: Request;
  /** Cloudflare Worker env â€" D1, KV, R2, DO, AI, etc. */
  env: E;
  /** Cloudflare execution context */
  ctx: ExecutionContext;
  /** Route parameters (e.g., { slug: 'hello-world' }) */
  params: Record<string, string>;
  /** Request-scoped state (set by middleware, read by load/actions) */
  locals: Record<string, any>;
  /** Parsed URL */
  url: URL;
}

export interface ActionContext<E = Env> extends RouteContext<E> {
  /** Submitted form payload for native and augmented form actions */
  formData: FormData;
}

export interface PageRenderResult {
  html: string;
  head?: string;
}

export type PageRenderOutput = string | PageRenderResult;

export type LoadHandler<E = Env> = (ctx: RouteContext<E>) => MaybePromise<Record<string, any>>;

export type NativeActionHandler<E = Env> = (ctx: ActionContext<E>) => MaybePromise<any>;

export type PositionalActionHandler<E = Env, Args extends any[] = any[]> = (
  ...args: [...Args, ActionContext<E>]
) => MaybePromise<any>;

export type ActionHandler<E = Env> =
  | NativeActionHandler<E>
  | PositionalActionHandler<E>
  | ((...args: any[]) => MaybePromise<any>);

export type RouteRpcHandler<E = Env> = (args: any[], env: E, ctx: RouteContext<E>) => MaybePromise<any>;

/** A compiled route module */
export interface RouteModule<E = Env> {
  /** Pattern string (e.g., '/todos', '/blog/:slug') */
  pattern: string;
  /** Load function â€" runs on GET, returns data for the template */
  load?: LoadHandler<E>;
  /** Form actions â€" keyed by action name */
  actions?: Record<string, ActionHandler<E>>;
  /** RPC functions - callable from the client through the Kuratchi Channel */
  rpc?: Record<string, RouteRpcHandler<E>>;
  /** Optional schemas for RPC inputs, keyed by function name */
  rpcSchemas?: Record<string, any>;
  /** Render function â€" returns route HTML and optional head content from data */
  render: (data: Record<string, any>) => PageRenderOutput;
  /** Layout name (default: 'default') */
  layout?: string;
}

/** HTTP methods supported by API routes */
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';

export interface ApiRouteManifest {
  kind?: 'api';
  pattern?: string;
  file?: string;
  methods?: HttpMethod[];
  summary?: string;
  description?: string;
  operationId?: string;
  tags?: string[];
  auth?: 'public' | 'optional' | 'required';
  params?: Record<string, unknown>;
  query?: Record<string, unknown>;
  body?: unknown;
  responses?: Record<string, unknown>;
  [key: string]: unknown;
}

/** A compiled API route module (route.ts) — returns raw Response objects */
export type ApiRouteHandler<E = Env> = (ctx: RouteContext<E>) => MaybePromise<Response>;

export interface ApiRouteModule<E = Env> {
  /** Pattern string (e.g., '/api/v1/health', '/api/v1/db/:name') */
  pattern: string;
  /** Marker that distinguishes API routes from page routes */
  __api: true;
  manifest?: ApiRouteManifest;
  /** Method handlers — keyed by HTTP method */
  [method: string]:
    | ApiRouteHandler<E>
    | string
    | boolean
    | ApiRouteManifest
    | undefined;
}

/** Layout module */
export interface LayoutModule {
  /** Render function â€" wraps page content */
  render: (data: { content: string; data: Record<string, any>; head?: string }) => string;
}

/** App configuration (internal â€" used by compiler-generated code) */
export interface AppConfig<E = Env> {
  /** Route modules â€" generated by compiler or defined manually */
  routes?: (RouteModule<E> | ApiRouteModule<E>)[];
  /** Layout modules â€" keyed by name */
  layouts?: Record<string, LayoutModule>;
  /** Static file directory (relative to project root) */
  publicDir?: string;
}

export interface DesktopWindowConfig {
  title?: string;
  width?: number;
  height?: number;
}

export interface DesktopRemoteBindingConfig {
  type: 'd1' | 'r2';
  remote?: boolean;
}

export interface DesktopConfig {
  /** Human-readable app name shown by the desktop host. */
  appName?: string;
  /** Stable app identifier used by the host/runtime. */
  appId?: string;
  /** Initial route loaded by the host. Defaults to '/'. */
  initialPath?: string;
  /** Single-window host settings. */
  window?: DesktopWindowConfig;
  /** Desktop-native bindings exposed by the host. */
  bindings?: {
    notifications?: boolean;
    files?: boolean;
    [key: string]: any;
  };
  /** Remote Cloudflare bindings the desktop runtime should proxy. */
  remoteBindings?: Record<string, DesktopRemoteBindingConfig>;
}

/**
 * Response-header security configuration. Supplied to the Vite plugin
 * (`koze({ security: { ... } })`) or the legacy CLI's `compile()`
 * options.
 *
 * Koze enforces origin integrity (strict same-origin on RPC, same-origin on actions)
 * and visibility boundaries (`_`-prefix private) unconditionally — those are not
 * configurable because they are the framework's contract with your app. Authentication
 * and authorization are your responsibility: use an auth library (e.g. `@kuratchi/auth`)
 * or inline guards inside your RPC/action handlers.
 *
 * The fields below are the response-header knobs the framework sets for you.
 */
export interface SecurityConfig {
  /**
   * Content Security Policy directive string.
   * Use the literal placeholder `{NONCE}` to opt into per-request nonces — the framework
   * will substitute it with a fresh nonce on every response and stamp the same nonce onto
   * every inline `<script>` it injects. Example:
   *   `"script-src 'self' 'nonce-{NONCE}'; object-src 'none'"`
   */
  contentSecurityPolicy?: string;
  /** Strict-Transport-Security header value */
  strictTransportSecurity?: string;
  /** Permissions-Policy header value */
  permissionsPolicy?: string;
}





/** Middleware pipeline context - shared across middleware step handlers */
export interface MiddlewareContext<E extends Env = Env> {
  request: Request;
  env: E;
  ctx: ExecutionContext;
  url: URL;
  params: Record<string, string>;
  locals: Record<string, any>;
}

export type MiddlewareNext = () => Promise<Response>;

export type MiddlewareErrorResult = Response | null | undefined | void;

export interface MiddlewareStep<E extends Env = Env> {
  request?: (ctx: MiddlewareContext<E>, next: MiddlewareNext) => Promise<Response> | Response;
  route?: (ctx: MiddlewareContext<E>, next: MiddlewareNext) => Promise<Response> | Response;
  response?: (ctx: MiddlewareContext<E>, response: Response) => Promise<Response> | Response;
  error?: (ctx: MiddlewareContext<E>, error: unknown) => Promise<MiddlewareErrorResult> | MiddlewareErrorResult;
}

export type MiddlewareDefinition<E extends Env = Env> = Record<string, MiddlewareStep<E>>;

/** @deprecated Use MiddlewareContext */
export type RuntimeContext<E extends Env = Env> = MiddlewareContext<E>;
/** @deprecated Use MiddlewareNext */
export type RuntimeNext = MiddlewareNext;
/** @deprecated Use MiddlewareErrorResult */
export type RuntimeErrorResult = MiddlewareErrorResult;
/** @deprecated Use MiddlewareStep */
export type RuntimeStep<E extends Env = Env> = MiddlewareStep<E>;
/** @deprecated Use MiddlewareDefinition */
export type RuntimeDefinition<E extends Env = Env> = MiddlewareDefinition<E>;
