import * as fs from 'node:fs';
import * as path from 'node:path';

import type {
  PipelineConfigEntry,
  PipelineR2DataCatalogSinkConfig,
  PipelineSchemaConfig,
  PipelineSchemaField,
} from './compiler-shared.js';

export interface WritePipelineArtifactsOptions {
  projectDir: string;
  pipelines: PipelineConfigEntry[];
  writeFile?: (filePath: string, content: string) => void;
}

interface NormalizedSchemaFile {
  fields: PipelineSchemaField[];
}

export function writePipelineArtifacts(opts: WritePipelineArtifactsOptions): void {
  const writeFile = opts.writeFile ?? defaultWriteFile;

  for (const entry of opts.pipelines) {
    if (!entry.schema && !entry.sink && !entry.sql) continue;

    const outDir = path.join(opts.projectDir, '_cloudflare', 'pipelines', entry.name);
    if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

    const schemaPath = path.join(outDir, 'schema.json');
    const sqlPath = path.join(outDir, 'pipeline.sql');
    const readmePath = path.join(outDir, 'README.md');
    const setupPath = path.join(outDir, 'setup.ps1');

    const schemaFile = entry.schema ? normalizeSchema(entry.schema) : null;
    if (schemaFile) {
      writeFile(schemaPath, JSON.stringify(schemaFile, null, 2) + '\n');
    }

    const sql = entry.sql ?? (entry.sink ? generatePipelineSql(entry, entry.sink) : null);
    if (sql) {
      writeFile(sqlPath, ensureTrailingNewline(sql));
    }

    writeFile(readmePath, generateReadme({
      entry,
      schemaPath: schemaFile ? toProjectPath(opts.projectDir, schemaPath) : null,
      sqlPath: sql ? toProjectPath(opts.projectDir, sqlPath) : null,
      setupPath: toProjectPath(opts.projectDir, setupPath),
    }));
    writeFile(setupPath, generateSetupScript({
      entry,
      schemaPath: schemaFile ? toProjectPath(opts.projectDir, schemaPath) : null,
      sqlPath: sql ? toProjectPath(opts.projectDir, sqlPath) : null,
    }));
  }
}

function normalizeSchema(schema: PipelineSchemaConfig): NormalizedSchemaFile {
  const fields = Array.isArray(schema)
    ? schema
    : Object.entries(schema).map(([name, value]) => {
      if (typeof value === 'string') {
        return { name, type: value };
      }
      return { name, ...value };
    });

  return {
    fields: fields.map((field) => {
      const rawType = String(field.type);
      const requiredFromType = rawType.endsWith('!');
      const type = requiredFromType ? rawType.slice(0, -1) : rawType;
      return {
        ...field,
        type,
        required: field.required ?? requiredFromType,
      };
    }),
  };
}

function generatePipelineSql(entry: PipelineConfigEntry, sink: PipelineR2DataCatalogSinkConfig): string {
  return [
    `INSERT INTO ${sink.name ?? `${entry.name.replace(/-/g, '_')}_sink`}`,
    'SELECT *',
    `FROM ${entry.pipeline};`,
    '',
  ].join('\n');
}

function generateReadme(opts: {
  entry: PipelineConfigEntry;
  schemaPath: string | null;
  sqlPath: string | null;
  setupPath: string;
}): string {
  const { entry } = opts;
  const sink = entry.sink;
  const lines = [
    `# ${entry.name} pipeline`,
    '',
    `Generated by Koze from \`${entry.file}\`. Change the \`.pipeline.ts\` file, then rerun Vite or the compiler to regenerate these files.`,
    '',
    'Cloudflare owns the remote stream, sink, and pipeline resources. Kuratchi keeps the local declaration, Worker binding, schema, SQL, and setup commands in sync in this visible `_cloudflare/` handoff folder.',
    '',
    '## Files',
    '',
  ];

  if (opts.schemaPath) lines.push(`- \`${opts.schemaPath}\`: stream schema for \`${entry.pipeline}\`.`);
  if (opts.sqlPath) lines.push(`- \`${opts.sqlPath}\`: SQL used when creating the Cloudflare Pipeline resource.`);
  lines.push(`- \`${opts.setupPath}\`: Wrangler commands for first-time provisioning.`);

  if (sink) {
    lines.push(
      '',
      '## Destination',
      '',
      `- Stream: \`${entry.pipeline}\``,
      `- Pipeline: \`${entry.pipelineName ?? entry.name}\``,
      `- Sink: \`${sink.name ?? `${entry.name.replace(/-/g, '_')}_sink`}\``,
      `- Bucket: \`${sink.bucket}\``,
      `- Table: \`${sink.namespace ?? 'default'}.${sink.table}\``,
    );
  }

  lines.push('');
  return lines.join('\n');
}

function generateSetupScript(opts: {
  entry: PipelineConfigEntry;
  schemaPath: string | null;
  sqlPath: string | null;
}): string {
  const { entry } = opts;
  const sink = entry.sink;
  const lines = [
    '# Generated by Koze. Do not edit this file directly.',
    `# Source: ${entry.file}`,
    '',
  ];

  if (sink?.type === 'r2-data-catalog') {
    lines.push(
      '# R2 Data Catalog sinks require an R2 Admin Read & Write token.',
      '# Set this only in your shell before running the sink command.',
      '# $env:WRANGLER_R2_SQL_AUTH_TOKEN = "<token>"',
      '',
      `npx wrangler r2 bucket create ${psArg(sink.bucket)}`,
      `npx wrangler r2 bucket catalog enable ${psArg(sink.bucket)}`,
      '',
    );
  }

  const streamArgs = [
    'npx wrangler pipelines streams create',
    psArg(entry.pipeline),
    opts.schemaPath ? `--schema-file ${psArg(opts.schemaPath)}` : '',
    '--http-enabled false',
  ].filter(Boolean);
  lines.push(streamArgs.join(' '));

  if (sink?.type === 'r2-data-catalog') {
    const sinkArgs = [
      'npx wrangler pipelines sinks create',
      psArg(sink.name ?? `${entry.name.replace(/-/g, '_')}_sink`),
      '--type r2-data-catalog',
      `--bucket ${psArg(sink.bucket)}`,
      `--namespace ${psArg(sink.namespace ?? 'default')}`,
      `--table ${psArg(sink.table)}`,
      '--catalog-token $env:WRANGLER_R2_SQL_AUTH_TOKEN',
      sink.rollInterval !== undefined ? `--roll-interval ${sink.rollInterval}` : '',
      sink.rollSize !== undefined ? `--roll-size ${sink.rollSize}` : '',
      sink.compression ? `--compression ${psArg(sink.compression)}` : '',
      sink.targetRowGroupSize !== undefined ? `--target-row-group-size ${sink.targetRowGroupSize}` : '',
    ].filter(Boolean);
    lines.push(sinkArgs.join(' '));
  }

  if (opts.sqlPath) {
    lines.push(`npx wrangler pipelines create ${psArg(entry.pipelineName ?? entry.name)} --sql-file ${psArg(opts.sqlPath)}`);
  }

  lines.push('');
  return lines.join('\n');
}

function defaultWriteFile(filePath: string, content: string): void {
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf-8') === content) return;
  fs.writeFileSync(filePath, content, 'utf-8');
}

function toProjectPath(projectDir: string, filePath: string): string {
  return path.relative(projectDir, filePath).replace(/\\/g, '/');
}

function ensureTrailingNewline(value: string): string {
  return value.endsWith('\n') ? value : value + '\n';
}

function psArg(value: string): string {
  if (/^[A-Za-z0-9_./:-]+$/.test(value)) return value;
  return `'${value.replace(/'/g, "''")}'`;
}
