import type { GenerateRoutesModuleOptions, RoutesModuleFeatureBlocks } from './routes-module-types.js';
import { createPreparedRouter } from '../runtime/router.js';

export function buildRoutesModuleRuntimeShell(
  opts: GenerateRoutesModuleOptions,
  blocks: RoutesModuleFeatureBlocks,
): string {
  const layoutBlock = opts.compiledLayout ?? 'function __layout(content, _head = \'\') { return content; }';
  const layoutActionsBlock = opts.compiledLayoutActions
    ? `const __layoutActions = ${opts.compiledLayoutActions};`
    : 'const __layoutActions = {};';
  const componentBlock = opts.compiledComponents.length > 0 ? `// Components\n\n${opts.compiledComponents.join('\n\n')}\n` : '';
  const customErrorFunctions = Array.from(opts.compiledErrorPages.entries())
    .map(([status, fn]) => fn)
    .join('\n\n');
  const customErrorEntries = Array.from(opts.compiledErrorPages.keys())
    .map((status) => `  ${status}: __error_${status},`)
    .join('\n');
  const initializeRequestBody = [
    blocks.doResolverInit ? '    __initDoResolvers();' : '',
  ].filter(Boolean).join('\n');
  const preparedRouter = JSON.stringify(createPreparedRouter(opts.routePatterns));

  return `// Generated by Koze compiler - do not edit.
${opts.isDev ? '\nglobalThis.__koze_DEV__ = true;\n' : ''}
${blocks.workerImport}
import { createGeneratedWorker } from '${opts.runtimeWorkerImport}';
${blocks.contextImport}
${blocks.middlewareImport ? blocks.middlewareImport + '\n' : ''}${blocks.doImports ? blocks.doImports + '\n' : ''}${opts.serverImports.join('\n')}
${blocks.workflowStatusRpc}
${blocks.pipelineRegistry}

// Assets

const __assets = {
${opts.compiledAssets.map((asset) => `  ${JSON.stringify(asset.name)}: { content: ${JSON.stringify(asset.content)}, mime: ${JSON.stringify(asset.mime)}, etag: ${JSON.stringify(asset.etag)} }`).join(',\n')}
};

// Layout

${layoutBlock}

${layoutActionsBlock}

// Error pages

${customErrorFunctions ? '// Custom error page overrides (user-created NNN.html)\n' + customErrorFunctions + '\n' : ''}const __customErrors = {
${customErrorEntries}
};

${componentBlock}${blocks.doResolverInit}${blocks.doClassCode}
// Route definitions

const routes = [
${opts.compiledRoutes.join(',\n')}
];

const __preparedRouter = ${preparedRouter};

const __middlewareDef = (typeof __kozeMiddleware !== 'undefined' && __kozeMiddleware && typeof __kozeMiddleware === 'object') ? __kozeMiddleware : {};

async function __initializeRequest(ctx) {
${initializeRequestBody || '    return;'}
}

export default createGeneratedWorker({
  routes,
  preparedRouter: __preparedRouter,
  layout: __layout,
  layoutActions: __layoutActions,
  assetsPrefix: ${JSON.stringify(opts.assetsPrefix)},
  assets: __assets,
  errorPages: __customErrors,
  middlewareDefinition: __middlewareDef,
  initializeRequest: __initializeRequest,
  security: {
    contentSecurityPolicy: ${JSON.stringify(opts.securityConfig.contentSecurityPolicy)},
    strictTransportSecurity: ${JSON.stringify(opts.securityConfig.strictTransportSecurity)},
    permissionsPolicy: ${JSON.stringify(opts.securityConfig.permissionsPolicy)},
  },
});
`;
}
